# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42119f80fd89487718eec7c0282582ec0afe29bce68b9446d4e8d45c1e9864cee198a4a30df74968a2ffaaec864ae8b70a573942bbc64b21dd9abaaacdaabaa1

test:
  secret_key_base: d714ef3b54b45b3ad4c5e6ab33bd593d7bcaf9ba2206d34f2c0f02656b5f4692e070b8cc6b31d08299a4ce7b2862e4bf59726510fb535b28faf432d2dc1e2aaa

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
